server:
  port: 2008
  context-path: /

eureka:
  instance:
    hostname: localhost  #eureka客户端主机实例名称
    appname: springcloud-ribbon-client  #客户端服务名
    instance-id: springcloud-ribbon-client:2008 #客户端实例名称
    prefer-ip-address: true #显示IP
  client:
    service-url:
      defaultZone: http://localhost:2001/eureka #把服务注册到eureka注册中心

info:
    groupId: com.baiyun
    artifactId: springcloud-ribbon-client
    version: 1.0.0
    负责人: abcabc
    联系电话: 11111111